# Spring
spring:
  config:
    import:
      - env.properties
      - optional:env.yml
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  thymeleaf:
    check-template-location: false
  mvc:
    log-request-details: true

  data:
    web:
      pageable:
        one-indexed-parameters: true


# Logging
logging:
  level:
    web: info
    com.battlecruisers.yanullja: info
    org:
      hibernate:
        sql: info
        type.descriptor.sql: info
      springframework: info
      springframework.web: info
    root: info

# Logbook
logbook:
  format:
    style: http
  write:
    max-body-size: 1024

